version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:


services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: konfuzer/kittygram_backend:latest
    env_file: .env
    volumes:
      - media_volume:/app/media
      - static_volume:/app/static
    depends_on:
      - db
    environment:
      - KITTYGRAM_API_URL=https://kittygram.hopto.org/api/

  frontend:
    image: konfuzer/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static

  gateway:
    image: konfuzer/kittygram_gateway:latest
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static
      - media_volume:/media
